export const GET_ANIMALS = 'GET_ANIMALS';
export const GET_ANIMALS_FAILURE='GET_ANIMALS_FAILURE'
export const GET_ANIMALS_SUCCESS='GET_ANIMALS_SUCCESS'
export const NEW_ANIMAL = 'NEW_ANIMAL';
export const DELETE_ANIMAL = 'DELETE_ANIMAL';
export const EDIT_ANIMAL = 'EDIT_ANIMAL';
export const SHOW_FORM = 'SHOW_FORM';
export const HIDE_FORM = 'HIDE_FORM';